ListProdukDibeli_PengantaranFarmasi/urls.py
from django.contrib import admin
from django.urls import path
from .views import *

urlpatterns = [
    path('produk_dibeli/create/', createProdukDibeli, name='createProdukDibeli'),
    path('produk_dibeli/update/<str:id_apotek>-<str:id_produk>-<str:id_transaksi_pembelian>/', updateProdukDibeli, name='updateProdukDibeli'),
    path('produk_dibeli/delete/<str:id_apotek>-<str:id_produk>-<str:id_transaksi_pembelian>/', deleteProdukDibeli, name='deleteProdukDibeli'),
    path('produk_dibeli/', readProdukDibeli, name='readProdukDibeli'),

    path('pengantaran_farmasi/create/', createPengantaranFarmasi, name='createPengantaranFarmasi'),
    path('pengantaran_farmasi/update/<str:id_pengantaran>/', updatePengantaranFarmasi, name='updatePengantaranFarmasi'),
    path('pengantaran_farmasi/delete/<str:id_pengantaran>/', deletePengantaranFarmasi, name='deletePengantaranFarmasi'),
    path('pengantaran_farmasi/', readPengantaranFarmasi, name='readPengantaranFarmasi'),
]

TK4/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('login.urls')),
    path('', include('Transaksi_Pembelian.urls')),
    path('', include(('ListProdukDibeli_PengantaranFarmasi.urls','produk_dibeli'), namespace='produk_dibeli')),
    path('', include(('ListProdukDibeli_PengantaranFarmasi.urls', 'pengantaran_farmasi'), namespace='pengantaran_farmasi')),
    path('balaipengobatan/', include(('BalaiPengobatan_Obat.urls', 'balaipengobatan'), namespace='balaipengobatan')),
    path('obat/', include(('BalaiPengobatan_Obat.urls', 'obat'), namespace='obat')),
    path('apotek/', include('apotek.urls')),
    path('produkApotek/', include('produkApotek.urls')),
    path('', include('TransaksiResep_AlatMedis.urls'))
]

ListProdukDibeli_PengantaranFarmasi/models.py
from django.db import models

# Create your models here.

ListProdukDibeli_PengantaranFarmasi/forms.py
from django import forms
from django.db import connection
from collections import namedtuple

def namedtuplefetchall(cursor):
    "Return all rows from a cursor as a namedtuple"
    desc = cursor.description
    nt_result = namedtuple('Result', [col[0] for col in desc])
    return [nt_result(*row) for row in cursor.fetchall()]

def produkDibeliChoice():
    cursor = connection.cursor()
    cursor.execute("set search_path to farmakami")
    cursor.execute("select id_apotek from apotek order by id_apotek::int")
    apotek = namedtuplefetchall(cursor)
    cursor.execute("select id_produk from produk order by id_produk::int")
    produk = namedtuplefetchall(cursor)
    cursor.execute("select id_transaksi_pembelian from transaksi_pembelian order by id_transaksi_pembelian::int")
    transaksi_pembelian = namedtuplefetchall(cursor)
    apotek_choice = []
    produk_choice = []
    transaksi_pembelian_choice = []

    idx_string = ""

    for a in apotek:
        idx_string = str(a.id_apotek)
        apotek_choice.append((idx_string, idx_string))
        
    for a in produk:
        idx_string = str(a.id_produk)
        produk_choice.append((idx_string, idx_string))

    for a in transaksi_pembelian:
        idx_string = str(a.id_transaksi_pembelian)
        transaksi_pembelian_choice.append((idx_string, idx_string))

    argument = [
        apotek_choice,
        produk_choice,
        transaksi_pembelian_choice
    ]
    return argument

def pengantaranFarmasiChoice():
    cursor = connection.cursor()
    cursor.execute("set search_path to farmakami")
    cursor.execute("select id_transaksi_pembelian from transaksi_pembelian order by id_transaksi_pembelian::int")
    transaksi_pembelian = namedtuplefetchall(cursor)
    cursor.execute("select id_kurir from kurir order by id_kurir::int")
    kurir = namedtuplefetchall(cursor)
    transaksi_pembelian_choice = []
    kurir_choice = []

    idx_string = ""

    for a in kurir:
        idx_string = str(a.id_kurir)
        kurir_choice.append((idx_string, idx_string))
        
    for a in transaksi_pembelian:
        idx_string = str(a.id_transaksi_pembelian)
        transaksi_pembelian_choice.append((idx_string, idx_string))

    argument = [
        transaksi_pembelian_choice,
        kurir_choice
    ]

    return argument

choicesProdukDibeli = produkDibeliChoice()
choicesPengantaranFarmasi = pengantaranFarmasiChoice()

class CreateProdukDibeli(forms.Form):
    id_apotek = forms.CharField(label = 'ID Apotek', required = True, widget=forms.Select(choices=choicesProdukDibeli[0]))
    id_produk = forms.CharField(label = 'ID Produk', required = True, widget=forms.Select(choices=choicesProdukDibeli[1]))
    id_transaksi_pembelian = forms.CharField(label = 'ID Transaksi Pembelian', required = True, widget=forms.Select(choices=choicesProdukDibeli[2]))
    jumlah = forms.IntegerField(label = 'Jumlah yang Dibeli')

class UpdateProdukDibeli(forms.Form):
    id_apotek = forms.CharField(label = 'ID Apotek', widget = forms.Select(attrs={'readonly':'readonly'}, choices=choicesProdukDibeli[0]), required = True)
    id_produk = forms.CharField(label = 'ID Produk', widget = forms.Select(attrs={'readonly':'readonly'}, choices=choicesProdukDibeli[1]), required = True)
    id_transaksi_pembelian = forms.CharField(label = 'ID Transaksi Pembelian', required = True, widget=forms.Select(choices=choicesProdukDibeli[2]))
    jumlah = forms.IntegerField(label = 'Jumlah yang Dibeli', widget = forms.NumberInput(), initial = 10)

class CreatePengantaranFarmasi(forms.Form):
    id_kurir = forms.CharField(label = 'ID Kurir', widget = forms.Select(choices=choicesPengantaranFarmasi[1]), required = True)
    id_transaksi_pembelian = forms.CharField(label = 'ID Transaksi Pembelian', widget=forms.Select(choices=choicesPengantaranFarmasi[0]), required = True)
    waktu = forms.DateTimeField(label = 'Tanggal dan Waktu (Format yyyy-mm-dd hh:mm:ss)', required = True, initial="Now")
    biaya_kirim = forms.IntegerField(label = 'Biaya Kirim', required = True, initial = 0)

class UpdatePengantaranFarmasi(forms.Form):
    id_pengantaran = forms.CharField(label = 'ID Pengantaran', widget = forms.Select(choices=choicesPengantaranFarmasi[0]), required = True)
    id_kurir = forms.CharField(label = 'ID Kurir', widget = forms.Select(choices=choicesPengantaranFarmasi[1]), required = True)
    id_transaksi_pembelian = forms.CharField(label = 'ID Transaksi Pembelian', widget = forms.Select(choices=choicesPengantaranFarmasi[0]), required = True)
    waktu = forms.DateTimeField(label = 'Tanggal dan Waktu', required = True)
    status_pengantaran = forms.CharField(label = 'Status Pengantaran', required = True)
    biaya_kirim = forms.IntegerField(label = 'Biaya Kirim', required = True)

ListProdukDibeli_PengantaranFarmasi/views.py
from django.shortcuts import render, reverse, redirect
from .forms import *
from django.db import connection
from collections import namedtuple
from django.http import HttpResponseRedirect

# Create your views here.
def namedtuplefetchall(cursor):
    "Return all rows from a cursor as a namedtuple"
    desc = cursor.description
    nt_result = namedtuple('Result', [col[0] for col in desc])
    return [nt_result(*row) for row in cursor.fetchall()]

# LIST PRODUK DIBELI

def readProdukDibeli(request):
    cursor = connection.cursor()
    # checkPrivilege(request.session)
    roleAdmin = False
    roleKonsumen = False
    roleKurir = False
    roleCS = False
    try:
        if (request.session['role'] == 'Admin'):
            roleAdmin = True
        if (request.session['role'] == 'Konsumen'):
            roleKonsumen = True
        if (request.session['role'] == 'Kurir'):
            roleKurir = True
        if (request.session['role'] == 'CS'):
            roleCS = True
        email = str(request.session['email'])
    except:
        return reverse('login')

    cursor.execute("set search_path to farmakami")

    # if (roleKonsumen):
    #     # query = "select * from "
    #     # query += "list_transaksi_pembelian l, transaksi_pembelian t, konsumen k "
    #     # query += "where t.id_konsumen = k.id_konsumen "
    #     # query += "and k.email = " + email + " order by id_apotek::int"
    #     cursor.execute(query)
    # else:
    cursor.execute("select * from list_produk_dibeli order by id_apotek::int")
    hasil = namedtuplefetchall(cursor)

    argument = {
        'hasil' : hasil,
        'roleAdmin' : roleAdmin,
        'roleKonsumen' : roleKonsumen,
        'roleKurir' : roleKurir,
        'roleCS' : roleCS
    }
    return render(request, "readProdukDibeli.html", argument)

def createProdukDibeli(request):
    message = ""
    id_apotek = '1'
    id_produk = '1'
    id_transaksi_pembelian = '1'
    if request.method =='POST':
        try:
            input = request.POST
            cursor = connection.cursor()
            cursor.execute("set search_path to farmakami")
            cursor.execute("insert into list_produk_dibeli values ("+input['jumlah']+",'"+input['id_apotek']+"','"+input['id_produk']+"','"+input['id_transaksi_pembelian']+"')")
            return redirect('/produk_dibeli/')
        except:
            message = "ID Apotek " + input['id_apotek'] + " tidak memiliki ID Produk " + input['id_produk']
            id_apotek = input['id_apotek']
            id_produk = input['id_produk']
            id_transaksi_pembelian = input['id_transaksi_pembelian']
            pass

    
    form = CreateProdukDibeli(initial={
        'id_apotek' : id_apotek,
        'id_produk' : id_produk,
        'id_transaksi_pembelian' : id_transaksi_pembelian,
    }) 
    args = {
        'form': form,
        'message': message,
    }
    return render(request, 'createProdukDibeli.html', args)

def updateProdukDibeli(request, id_apotek, id_produk, id_transaksi_pembelian):
    message = ""
    if request.method =='POST':
        try:
            input = request.POST
            cursor = connection.cursor()
            cursor.execute("set search_path to farmakami")
            query = "update list_produk_dibeli"
            query += (" set id_transaksi_pembelian = '" + input['id_transaksi_pembelian'] + "' ")
            query += (", jumlah = '" + input['jumlah'] + "' ")
            query += ("where id_apotek = '" + id_apotek + "' ")
            query += ("and id_produk = '" + id_produk +"' ")
            cursor.execute(query)
            return redirect('/produk_dibeli/')
        except:
            message = "Terjadi kesalahan saat update produk dibeli"
            pass

    cursor = connection.cursor()
    cursor.execute("set search_path to farmakami")
    query = "select jumlah from "
    query += "list_produk_dibeli "
    query += ("where id_apotek = '" + id_apotek + "' ")
    query += ("and id_produk = '" + id_produk + "' ")
    query += ("and id_transaksi_pembelian = '" + id_transaksi_pembelian + "' ")
    cursor.execute(query)
    hasil = namedtuplefetchall(cursor)

    form = UpdateProdukDibeli(initial={
        'id_apotek' : id_apotek,
        'id_produk' : id_produk,
        'id_transaksi_pembelian' : id_transaksi_pembelian,
        'jumlah' : hasil[0].jumlah,
    }) 
    # form.fields['id_apotek'].widget = forms.HiddenInput()
    # form.fields['id_produk'].widget = forms.HiddenInput()
    form.fields['id_apotek'].widget.attrs['disabled'] = 'disabled'
    form.fields['id_produk'].widget.attrs['disabled'] = 'disabled'
    args = {
        'form': form,
        'id_apotek': id_apotek,
        'id_produk': id_produk,
        'id_transaksi_pembelian': id_transaksi_pembelian,
        'message' : message,
    }

    return render(request, "updateProdukDibeli.html", args)

def deleteProdukDibeli(request, id_apotek, id_produk, id_transaksi_pembelian):
    cursor = connection.cursor()
    # id_apotek = kwargs['id_apotek']
    # id_produk = kwargs['id_produk']
    # id_transaksi_pembelian = kwargs['id_transaksi_pembelian']
    print(id_apotek)
    cursor.execute("set search_path to farmakami")
    cursor.execute("delete from list_produk_dibeli where id_transaksi_pembelian = '"+id_transaksi_pembelian+"' and id_apotek = '"+id_apotek+"' and id_produk ='"+id_produk+"'")
    return redirect('/produk_dibeli/')

# PENGANTARAN FARMASI

def readPengantaranFarmasi(request):
    cursor = connection.cursor()
    # checkPrivilege(request.session)
    roleAdmin = False
    roleKonsumen = False
    roleKurir = False
    roleCS = False
    try:
        if (request.session['role'] == 'Admin'):
            roleAdmin = True
        if (request.session['role'] == 'Konsumen'):
            roleKonsumen = True
        if (request.session['role'] == 'Kurir'):
            roleKurir = True
        if (request.session['role'] == 'CS'):
            roleCS = True
        email = str(request.session['email'])
    except:
        return reverse('login')

    cursor.execute("set search_path to farmakami")
    if (roleKurir):
        query = "select p.* from "
        query += "pengantaran_farmasi p, kurir k "
        query += ("where k.email = '" + email +"' ")
        query += ("and k.id_kurir = p.id_kurir ")
        query += "order by p.id_pengantaran::int"
        cursor.execute(query)
    else:
        cursor.execute("select * from pengantaran_farmasi order by id_pengantaran::int")

    hasil = namedtuplefetchall(cursor)
    argument = {
        'hasil' : hasil,
        'roleAdmin' : roleAdmin,
        'roleKonsumen' : roleKonsumen,
        'roleKurir' : roleKurir,
        'roleCS' : roleCS
    }
    return render(request, "readPengantaranFarmasi.html", argument)

def max_index():
    cursor = connection.cursor()
    cursor.execute("set search_path to farmakami")
    cursor.execute("select id_pengantaran from pengantaran_farmasi order by id_pengantaran::int")
    result = namedtuplefetchall(cursor)
    idx = []
    for a in result:
        result_string = str(a)
        idx_string = result_string[23:-2]
        idx.append(int(idx_string))
    return idx[-1]

def createPengantaranFarmasi(request):
    idx_next = max_index() + 1

    print(idx_next)
    if request.method =='POST':
        try:
            cursor = connection.cursor()
            cursor.execute("set search_path to farmakami")
            input = request.POST
            cursor.execute("insert into pengantaran_farmasi values ('"+str(idx_next)+"','"+input['id_kurir']+"','"+input['id_transaksi_pembelian']+"','"+input['waktu']+"', 'Processing',"+input['biaya_kirim']+",0)")
            return redirect('/pengantaran_farmasi/')
        except:
            message = "Terjadi kesalahan saat membuat item"
            pass

    form = CreatePengantaranFarmasi()
    args = {'form': form}
    return render(request, 'createPengantaranFarmasi.html', args)

def updatePengantaranFarmasi(request, id_pengantaran):
    message = ""
    if request.method =='POST':
        try:
            input = request.POST
            cursor = connection.cursor()
            cursor.execute("set search_path to farmakami")
            query = "update pengantaran_farmasi "
            query += ("set id_kurir = '" + input['id_kurir'] + "' ")
            query += (", id_transaksi_pembelian = '" + input['id_transaksi_pembelian'] + "' ")
            query += (", waktu = '" + input['waktu'] + "' ")
            query += (", biaya_kirim = '" + input['biaya_kirim'] + "' ")
            query += (", status_pengantaran = '" + input['status_pengantaran'] + "' ")
            query += ("where id_pengantaran = '" + id_pengantaran + "' ")
            cursor.execute(query)
            return redirect('/pengantaran_farmasi/')
        except:
            message = "Maaf, barang tersebut sedang diantar"
            pass
    
    cursor = connection.cursor()
    cursor.execute("set search_path to farmakami")
    query = "select * from "
    query += "pengantaran_farmasi "
    query += ("where id_pengantaran = '" + id_pengantaran + "' ")
    cursor.execute(query)
    hasil = namedtuplefetchall(cursor)
    form = UpdatePengantaranFarmasi(initial={
        'id_pengantaran': id_pengantaran,
        'id_kurir': hasil[0].id_kurir,
        'id_transaksi_pembelian': hasil[0].id_transaksi_pembelian,
        'waktu': hasil[0].waktu,
        'status_pengantaran': hasil[0].status_pengantaran,
        'biaya_kirim': hasil[0].biaya_kirim,
    })
    form.fields['id_pengantaran'].widget.attrs['disabled'] = 'disabled'
    args = {
        'form': form,
        'id_pengantaran': id_pengantaran,
        'message' : message,
    }
    return render(request, "updatePengantaranFarmasi.html", args)

def deletePengantaranFarmasi(request, id_pengantaran):
    id_pengantaran = str(id_pengantaran)
    print(id_pengantaran)
    cursor = connection.cursor()
    cursor.execute("set search_path to farmakami")

ListProdukDibeli_PengantaranFarmasi/templates/createPengantaranFarmasi.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    Create Pengantaran Farmasi
{% endblock title %}

{% block content %}
<div class="container justify-content-center align-items-center">
  <h1 class="list_title">Create Pengantaran Farmasi</h1>
  <h2 class="message">{{message}}</h2>

  <div class="row justify-content-center">
    <div class="login">      
      <form  method="POST" action="{% url 'pengantaran_farmasi:createPengantaranFarmasi' %}">
        {% csrf_token %}
        <!-- ID APOTEK -->
        <div class="loginForm">{{form.as_p}}</div>
        <br>

        <input type="submit" value="Create" name="tombol" class="mybutton">
      </form>
    </div>
  </div>
</div>
{% endblock content %}

ListProdukDibeli_PengantaranFarmasi/templates/createProdukDibeli.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    Create Produk Dibeli
{% endblock title %}


{% block content %}
<div class="container justify-content-center align-items-center">
  <h1 class="list_title">Create Produk Dibeli</h1>
  <h2 class="message">{{message}}</h2>
  <div class="row justify-content-center">
    <div class="login">      
      <form  method="POST" action="{% url 'produk_dibeli:createProdukDibeli' %}">
        {% csrf_token %}
        <!-- ID APOTEK -->
        <div class="loginForm">{{form.as_p}}</div>
        <br>

        <input type="submit" value="Create" name="tombol" class="mybutton">
      </form>
    </div>
  </div>
</div>
{% endblock content %}

ListProdukDibeli_PengantaranFarmasi/templates/readPengantaranFarmasi.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    Pengantaran Farmasi
{% endblock title %}


{% block content %}
<div class="container justify-content-center align-items-center">
    <h1 class="list_title">Pengantaran Farmasi</h1>
    <h2 class="message">{{message}}</h2>

    <div class="row justify-content-center">
        {% if roleAdmin %}
        <a href="{% url 'pengantaran_farmasi:createPengantaranFarmasi' %}" class="mybutton" role="button" style="margin-bottom: 30px;">Create Item</a>
        {% endif %}
        <table class="table table-hover table-striped">
            <thead>
                <tr>
                    <th scope="col">ID Pengantaran</th>
                    <th scope="col">ID Kurir</th>
                    <th scope="col">ID Transaksi Pembelian</th>
                    <th scope="col">Waktu</th>
                    <th scope="col">Status</th>
                    <th scope="col">Biaya Kirim</th>
                    <th scope="col">Total Kirim</th>
                    {% if roleAdmin or roleCS %}
                    <th scope="col">Edit</th>
                    <th scope="col">Delete</th>
                    {% endif %}
                </tr>
            </thead>
            <tbody>
            {%for row in hasil %}
                <tr class="table-striped">
                    <th scope="row">{{row.id_pengantaran}}</th>
                    <td>{{row.id_kurir}}</td>
                    <td>{{row.id_transaksi_pembelian}}</td>
                    <td>{{row.waktu}}</td>
                    <td>{{row.status_pengantaran}}</td>
                    <td>{{row.biaya_kirim}}</td>
                    <td>{{row.total_biaya}}</td>
                    {% if roleAdmin or roleCS %}
                    <td><a href="{% url 'pengantaran_farmasi:updatePengantaranFarmasi' row.id_pengantaran %}" class="mybutton butwhite" role="button">EDIT</a></td>
                    <td><a href="{% url 'pengantaran_farmasi:deletePengantaranFarmasi' row.id_pengantaran %}" class="mybutton butred" role="button">DELETE</a></td>
                    {% endif %}
                </tr>
            {% endfor %}
            </tbody>
        </table> 
    </div>
</div>
{% endblock content %}

ListProdukDibeli_PengantaranFarmasi/templates/readProdukDibeli.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    Produk Dibeli
{% endblock title %}


{% block content %}
<div class="container justify-content-center align-items-center">
    <h1 class="list_title">Produk Dibeli</h1>
    <h2 class="message">{{message}}</h2>

    <div class="row justify-content-center">
        {% if roleAdmin %}
        <a href="{% url 'produk_dibeli:createProdukDibeli' %}" class="mybutton" role="button" style="margin-bottom: 30px;">Create Item</a>
        {% endif %}
        <table class="table table-hover table-striped">
            <thead>
                <tr>
                    <th scope="col">ID Apotek</th>
                    <th scope="col">ID Produk</th>
                    <th scope="col">ID Transaksi Pembelian</th>
                    <th scope="col">Jumlah</th>
                    {% if roleAdmin %}
                    <th scope="col">Edit</th>
                    <th scope="col">Delete</th>
                    {% endif %}
                </tr>
            </thead>
            <tbody>
            {%for row in hasil %}
                <tr class="tebla-hover table-striped">
                    <th scope="row">{{row.id_apotek}}</th>
                    <td>{{row.id_produk}}</td>
                    <td>{{row.id_transaksi_pembelian}}</td>
                    <td>{{row.jumlah}}</td>
                    {% if roleAdmin %}
                    <td><a href="{% url 'produk_dibeli:updateProdukDibeli' row.id_apotek row.id_produk row.id_transaksi_pembelian %}" class="mybutton butwhite" role="button">EDIT</a></td>
                    <td><a href="{% url 'produk_dibeli:deleteProdukDibeli' row.id_apotek row.id_produk row.id_transaksi_pembelian %}" class="mybutton butred" role="button">DELETE</a></td>
                    {% endif %}
                </tr>   
            {% endfor %}
            </tbody>
        </table> 
    </div>
</div>
{% endblock content %}

ListProdukDibeli_PengantaranFarmasi/templates/updatePengantaranFarmasi.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    Update Pengantaran Farmasi
{% endblock title %}


{% block content %}
<div class="container justify-content-center align-items-center">
  <h1 class="list_title">Create Balai Pengobatan</h1>
  <h2 class="message">{{message}}</h2>
            
  <div class="row justify-content-center">
    <div class="login">   
        <form  method="POST" action="{% url 'produk_dibeli:updatePengantaranFarmasi' id_pengantaran %}">
          {% csrf_token %}
          <div class="loginForm">{{form.as_p}}</div>

          <input type="submit" value="Update" name="tombol" class="mybutton">
    </form>
  </div>
</div>
{% endblock content %}

ListProdukDibeli_PengantaranFarmasi/templates/updateProdukDibeli.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    Update Produk Dibeli
{% endblock title %}


{% block content %}
<div class="container justify-content-center align-items-center">
  <h1 class="list_title">Update Produk Dibeli</h1>
  <h2 class="message">{{message}}</h2>
  
    <div class="row justify-content-center">
      <div class="login">      
        <form  method="POST" action="{% url 'produk_dibeli:updateProdukDibeli' id_apotek id_produk id_transaksi_pembelian %}">
          {% csrf_token %}
          <!-- ID APOTEK -->
          <p>
            <!-- <label for="id_id_apotek">ID Apotek:</label> -->
            <!-- <div class="loginForm">
              <p>
                <label for="id_id_apotek">ID Apotek:</label>
                <input type="select">
                {{form.id_apotek}}
              </p>
            </div> -->
            <div class="loginForm">{{form.as_p}}</div>
          </p>
          <input type="submit" value="Update" name="tombol" class="mybutton">
        </form>
      </div>
    </div>
  </div>
{% endblock content %}