TK4/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('login.urls')),
    path('', include('Transaksi_Pembelian.urls')),
    path('', include(('ListProdukDibeli_PengantaranFarmasi.urls','produk_dibeli'), namespace='produk_dibeli')),
    path('', include(('ListProdukDibeli_PengantaranFarmasi.urls', 'pengantaran_farmasi'), namespace='pengantaran_farmasi')),
    path('balaipengobatan/', include(('BalaiPengobatan_Obat.urls', 'balaipengobatan'), namespace='balaipengobatan')),
    path('obat/', include(('BalaiPengobatan_Obat.urls', 'obat'), namespace='obat')),
    path('apotek/', include('apotek.urls')),
    path('produkApotek/', include('produkApotek.urls')),
    path('', include('TransaksiResep_AlatMedis.urls'))
]

produkApotek/urls.py
from django.urls import path, include
from django.contrib import admin
from .views import createProdukApotek, tableProdukApotek, updateProdukApotek, deleteProdukApotek

app_name = "produkApotek"
urlpatterns = [
    path('createProdukApotek', createProdukApotek, name="createProdukApotek"),
    path('tableProdukApotek', tableProdukApotek, name="tableProdukApotek"),
    path('updateProdukApotek/<str:id_apotek>/<str:id_produk>', updateProdukApotek, name="updateProdukApotek"),
    path('deleteProdukApotek/<str:id_apotek>/<str:id_produk>', deleteProdukApotek, name="deleteProdukApotek")
]

produkApotek/models.py
from django.db import models

# Create your models here.

produkApotek/forms.py
from django import forms

class produkApotekForms(forms.Form):
    hargaJual = forms.DecimalField(label='Harga Jual', min_value=0, initial=1000, widget=forms.NumberInput(attrs={'placeholder':'*Required'}))
    satuanPenjualan = forms.CharField(label='Satuan Penjualan', max_length=5, widget=forms.TextInput(attrs={'placeholder':'*Required'}))
    stok = forms.IntegerField(label='Stok', min_value=0, widget=forms.NumberInput(attrs={'placeholder':'*Required'}))


class updateProdukApotekForms(forms.Form):
    hargaJual = forms.DecimalField(label='Harga Jual', min_value=0, initial=1000)
    satuanPenjualan = forms.CharField(label='Satuan Penjualan', max_length=5)
    stok = forms.IntegerField(label='Stok', min_value=0)

produkApotek/views.py
from django.shortcuts import render, reverse, redirect
from .forms import *
from django.db import connection
from collections import namedtuple
from django.http import HttpResponseRedirect
from django.db import IntegrityError

#GENERAL FUNCTION
def namedtuplefetchall(cursor):
    "Return all rows from a cursor as a namedtuple"
    desc = cursor.description
    nt_result = namedtuple('Result', [col[0] for col in desc])
    return [nt_result(*row) for row in cursor.fetchall()]

#GET VALUE FUNCTION
def get_input_produk_apotek(request):
    input = request.POST
    harga_jual = input['hargaJual']
    satuan_penjualan = input['satuanPenjualan']
    stok = input['stok']
    return [harga_jual, satuan_penjualan, stok]

#CREATE PRODUK APOTEK FUNCTION
def createProdukApotek(request):
    message =""
    cursor = connection.cursor()
    cursor.execute("set search_path to farmakami")
    cursor.execute("select id_apotek from apotek order by id_apotek asc")
    id_apotek_view = namedtuplefetchall(cursor)
    cursor.execute("select id_produk from produk order by cast(id_produk as int)")
    id_produk_view = namedtuplefetchall(cursor)

    if request.method =='POST':
        input = get_input_produk_apotek(request)
        id_produk = request.POST['id_produk']
        id_apotek = request.POST['id_apotek']
        try :
            cursor.execute("insert into produk_apotek values ('"+input[0]+"','"+input[2]+"','"+input[1]+"','"+id_produk+"','"+id_apotek+"')")
            cursor.close()
            return redirect('/produkApotek/tableProdukApotek')
        except Exception as e:
            message = str(e)[80:]

    form = produkApotekForms()
    args = {
        'id_apotek': id_apotek_view,
        'id_produk': id_produk_view,
        'form': form,
        'message' : message
        }
    return render(request, "createProdukApotek.html", args)

#READ PRODUK APOTEK FUNCTION
def tableProdukApotek(request):
    cursor = connection.cursor()
    roleAdmin = False

    try:
        if (request.session['role'] == 'Admin'):
            roleAdmin = True
    except:
        return redirect('/')

    cursor.execute("set search_path to farmakami")
    cursor.execute("select * from produk_apotek order by cast(id_produk as int), id_apotek asc")
    hasil = namedtuplefetchall(cursor)
    cursor.close()
    argument = {
        'table' : hasil,
        'roleAdmin' : roleAdmin,
    }
    return render(request, "tableProdukApotek.html", argument)

#UPDATE PRODUK APOTEK FUNCTION
def updateProdukApotek(request, id_apotek, id_produk, success=True):
    message =""
    id_apotek = str(id_apotek)
    id_produk = str(id_produk)
    id_produk_new = str(id_apotek)
    id_apotek_new = str(id_produk)
    cursor = connection.cursor()
    cursor.execute("set search_path to farmakami")
    cursor.execute("select id_apotek from apotek order by id_apotek asc")
    id_apotek_view = namedtuplefetchall(cursor)
    cursor.execute("select id_produk from produk order by cast(id_produk as int)")
    id_produk_view = namedtuplefetchall(cursor)
    cursor.execute("select * from produk_apotek where id_apotek = '"+id_apotek+"' and id_produk = '"+id_produk+"'")
    hasil = namedtuplefetchall(cursor)
    hargaJual = hasil[0].harga_jual
    stok = hasil[0].stok
    satuanPenjualan = hasil[0].satuan_penjualan
    form = updateProdukApotekForms(initial={
        'hargaJual': hargaJual, 'satuanPenjualan': satuanPenjualan, 'stok': stok })
    
    if request.method == 'POST':
        input = get_input_produk_apotek(request)
        id_produk_new = request.POST['id_produk']
        id_apotek_new = request.POST['id_apotek']
        print(id_apotek_new)
        try :
            cursor.execute("update produk_apotek set harga_jual ='"+input[0]+"', stok ='"+input[2]+"', satuan_penjualan ='"+input[1]+"', id_produk='"+id_produk_new+"', id_apotek='"+id_apotek_new+"' where id_produk ='"+id_produk+"' and id_apotek ='"+id_apotek+"'")
            cursor.close()
            return redirect('/produkApotek/tableProdukApotek')
        except Exception as e:
            message = str(e)[80:]
            
    argument = {
        'form' : form,
        'message' : message,
        'idApotekForm' : id_apotek,
        'idProdukForm' : id_produk,
        'id_apotek': id_apotek_view,
        'id_produk': id_produk_view,
    }
    return render(request, "updateProdukApotek.html", argument)

#DELETE PRODUK APOTEK FUNCTION
def deleteProdukApotek(request, id_apotek, id_produk):
    id_apotek = str(id_apotek)
    id_produk = str(id_produk)
    cursor = connection.cursor()
    roleAdmin = False

    try:
        if (request.session['role'] == 'Admin'):
            roleAdmin = True
    except:
        return redirect('/')

    cursor.execute("set search_path to farmakami")
    cursor.execute("delete from produk_apotek where id_apotek = '"+id_apotek+"' and id_produk = '"+id_produk+"'")
    cursor.execute("select * from produk_apotek order by cast(id_produk as int), id_apotek asc")
    hasil = namedtuplefetchall(cursor)
    cursor.close()
    message = "Data berhasil terhapus"
    argument = {
        'table' : hasil,
        'roleAdmin' : roleAdmin,
        'message' : message
    }
    return render(request, "tableProdukApotek.html", argument)

produkApotek/templates/createProdukApotek.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    Create Produk Apotek
{% endblock title %}

{% block content %}
<div class="container justify-content-center align-items-center">
  <h1 class="list_title">Create Produk Apotek</h1>
  <h2 class="message">{{message}}</h2>

  <div class="row justify-content-center">
    <div class="login">    
      <form  method="POST" action="{% url 'produkApotek:createProdukApotek' %}">
        {% csrf_token %}
        <label class="label" style="color: white;" for="id_produk">ID Produk:</label>
        
        <select class="form-control" name="id_produk" id="id_produk" >
          {%for row in id_produk %}
          <option value="{{row.id_produk}}">{{row.id_produk}}</option>
          {% endfor %}
        </select>
        <br>
        <label class="label" style="color: white;" for="id_apotek">ID Apotek:</label>
        
        <select class="form-control" name="id_apotek" id="id_apotek" >
          {%for row in id_apotek %}
          <option value="{{row.id_apotek}}">{{row.id_apotek}}</option>
          {% endfor %}
        </select>
        <br>
        <div class="loginForm">{{form.as_p}}</div>
        <br>
        <input type="submit" value="Create" name="tombol" class="mybutton">
      </form>
    </div>
  </div>
</div>
{% endblock content %}

produkApotek/templates/tableProdukApotek.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    Produk Apotek
{% endblock title %}


{% block content %}
<div class="container justify-content-center align-items-center">
    <h1 class="list_title">Produk Apotek</h1>
    <h2 class="message">{{message}}</h2>
    <div class="row justify-content-center">
        {% if roleAdmin %}
        <a href="{% url 'produkApotek:createProdukApotek' %}" class="mybutton" role="button" style="margin-bottom: 30px;">Create Item</a>
        {% endif %}
        <table class="table table-hover table-striped">
            <thead class="text-center myTable">
                <tr>
                    <th style="text-align: center; vertical-align: middle;" scope="col">ID Produk</th>
                    <th style="text-align: center; vertical-align: middle;" scope="col">ID Apotek</th>
                    <th style="text-align: center; vertical-align: middle;" scope="col">Harga Jual</th>
                    <th style="text-align: center; vertical-align: middle;" scope="col">Satuan Penjualan </th>
                    <th style="text-align: center; vertical-align: middle;" scope="col">Stok</th>
                    {% if roleAdmin %}
                    <th style="text-align: center; vertical-align: middle;" scope="col">Edit</th>
                    <th style="text-align: center; vertical-align: middle;" scope="col">Delete</th>
                    {% endif %}
                </tr>
            </thead>
            <tbody class="text-center">
            {%for row in table %}
                <tr class="table-striped">
                <th scope="row">{{row.id_produk}}</th>
                <th scope="row">{{ row.id_apotek }}</th>
                <td>{{ row.harga_jual }}</td>
                <td>{{ row.satuan_penjualan }}</td>
                <td>{{ row.stok }}</td>
                {% if roleAdmin %}
                <td><a href="{% url 'produkApotek:updateProdukApotek' row.id_apotek row.id_produk %}" class="mybutton butwhite" role="button">EDIT</a></td>
                <td><a href="{% url 'produkApotek:deleteProdukApotek' row.id_apotek row.id_produk %}" class="mybutton butred" role="button">DELETE</a></td>
                {% endif %}
                </tr>
            {% endfor %}
            </tbody>
        </table> 
    </div>
</div>
{% endblock content %}

produkApotek/templates/updateProdukApotek.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    Update Produk Apotek
{% endblock title %}


{% block content %}
<div class="container justify-content-center align-items-center">
  <h1 class="list_title">Update Produk Apotek</h1>
  <h2 class="message">{{message}}</h2>

  <div class="row justify-content-center">
    <div class="login">   
      <form  method="POST" action="{% url 'produkApotek:updateProdukApotek' idApotekForm idProdukForm %}">
        {% csrf_token %}
        <label class="label" style="color: white;" for="id_produk">ID Produk:</label>
        
        <select class="form-control" name="id_produk" id="id_produk" >
          {%for row in id_produk %}
          <option value= "{{ idProdukForm }}" selected hidden>{{ idProdukForm }}</option>
          <option value="{{row.id_produk}}">{{row.id_produk}}</option>
          {% endfor %}
        </select>
        <br>
        <label class="label" style="color: white;" for="id_apotek">ID Apotek:</label>
        
        <select class="form-control" name="id_apotek" id="id_apotek" >
          {%for row in id_apotek %}
          <option value= "{{ idApotekForm }}" selected hidden>{{ idApotekForm }}</option>
          <option value="{{row.id_apotek}}">{{row.id_apotek}}</option>
          {% endfor %}
        </select>
        <br>
        <div class="loginForm">{{form.as_p}}</div>
        <br>
        <input type="submit" value="Update" name="tombol" class="mybutton">
      </form>
    </div>
  </div>
</div>
{% endblock content %}