BalaiPengobatan_Obat/urls.py
from django.urls import path, include
from django.contrib import admin
from .views import bpcreate, bplist, obatcreate, obatlist, updatebp, updateobat, deletebp, deleteobat

app_name = "balaipengobatan"
urlpatterns = [
    path('createBalaiPengobatan', bpcreate, name="bpcreate"),
    path('listBalaiPengobatan', bplist, name="bplist"),
    path('updateBalaiPengobatan/<str:id_balai>', updatebp, name="updatebp"),
    path('deleteBalaiPengobatan/<str:id_balai>', deletebp, name="deletebp"),
    path('createObat', obatcreate, name="obatcreate"),
    path('listObat', obatlist, name="obatlist"),
    path('updateObat/<str:id_obat>/<str:id_produk>/<str:id_merk_obat>', updateobat, name="updateobat"),
    path('deleteObat/<str:id_obat>/<str:id_produk>', deleteobat, name="deleteobat"),
]

ListProdukDibeli_PengantaranFarmasi/urls.py
from django.contrib import admin
from django.urls import path
from .views import *

urlpatterns = [
    path('produk_dibeli/create/', createProdukDibeli, name='createProdukDibeli'),
    path('produk_dibeli/update/<str:id_apotek>-<str:id_produk>-<str:id_transaksi_pembelian>/', updateProdukDibeli, name='updateProdukDibeli'),
    path('produk_dibeli/delete/<str:id_apotek>-<str:id_produk>-<str:id_transaksi_pembelian>/', deleteProdukDibeli, name='deleteProdukDibeli'),
    path('produk_dibeli/', readProdukDibeli, name='readProdukDibeli'),

    path('pengantaran_farmasi/create/', createPengantaranFarmasi, name='createPengantaranFarmasi'),
    path('pengantaran_farmasi/update/<str:id_pengantaran>/', updatePengantaranFarmasi, name='updatePengantaranFarmasi'),
    path('pengantaran_farmasi/delete/<str:id_pengantaran>/', deletePengantaranFarmasi, name='deletePengantaranFarmasi'),
    path('pengantaran_farmasi/', readPengantaranFarmasi, name='readPengantaranFarmasi'),
]

TK4/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('login.urls')),
    path('', include('Transaksi_Pembelian.urls')),
    path('', include(('ListProdukDibeli_PengantaranFarmasi.urls','produk_dibeli'), namespace='produk_dibeli')),
    path('', include(('ListProdukDibeli_PengantaranFarmasi.urls', 'pengantaran_farmasi'), namespace='pengantaran_farmasi')),
    path('balaipengobatan/', include(('BalaiPengobatan_Obat.urls', 'balaipengobatan'), namespace='balaipengobatan')),
    path('obat/', include(('BalaiPengobatan_Obat.urls', 'obat'), namespace='obat')),
    path('apotek/', include('apotek.urls')),
    path('produkApotek/', include('produkApotek.urls')),
    path('', include('TransaksiResep_AlatMedis.urls'))
]

apotek/urls.py
from django.urls import path, include
from django.contrib import admin
from .views import createApotek, tableApotek, updateApotek, deleteApotek

app_name = "apotek"
urlpatterns = [
    path('createApotek', createApotek, name="createApotek"),
    path('tableApotek', tableApotek, name="tableApotek"),
    path('updateApotek/<str:id_apotek>', updateApotek, name="updateApotek"),
    path('deleteApotek/<str:id_apotek>', deleteApotek, name="deleteApotek"),
]

login/urls.py
from django.contrib import admin
from django.urls import path
from .views import index, login, registerPengguna, registerPenggunaRole, insertAdmin, insertKurir, insertCS, profil, logout, insertKonsumen

urlpatterns = [
    path('', index, name='login'),
    path('Profil/', profil, name='profil'),
    path('Logout/', logout,  name='logout'),
    path('Home/', login),
    path('Register/', registerPengguna),
    path('RegisterRole/', registerPenggunaRole),
    path('insertAdmin/', insertAdmin),
    path('insertKurir/', insertKurir),
    path('insertCS/', insertCS),
    path('insertKonsumen/', insertKonsumen),
]

produkApotek/urls.py
from django.urls import path, include
from django.contrib import admin
from .views import createProdukApotek, tableProdukApotek, updateProdukApotek, deleteProdukApotek

app_name = "produkApotek"
urlpatterns = [
    path('createProdukApotek', createProdukApotek, name="createProdukApotek"),
    path('tableProdukApotek', tableProdukApotek, name="tableProdukApotek"),
    path('updateProdukApotek/<str:id_apotek>/<str:id_produk>', updateProdukApotek, name="updateProdukApotek"),
    path('deleteProdukApotek/<str:id_apotek>/<str:id_produk>', deleteProdukApotek, name="deleteProdukApotek")
]

login/models.py
from django.db import models

# Create your models here.

login/forms.py
from django import forms

class LoginForm(forms.Form):
    email = forms.CharField(label = 'Email', max_length=50)
    password = forms.CharField(label = 'Password',  widget=forms.PasswordInput, max_length=128)

class ChoiceRoleForm(forms.Form):
    CHOICES=[
        ('Admin','Admin'),
        ('Konsumen','Konsumen'),
        ('Kurir','Kurir'),
        ('CS','CS')]
    Role = forms.ChoiceField(choices=CHOICES, widget=forms.RadioSelect)

class AdminRoleForm(forms.Form):
    email = forms.CharField(label = 'Email' , max_length=50)
    password = forms.CharField(label = 'Password',  widget=forms.PasswordInput, max_length=128)
    nama_lengkap = forms.CharField(label = 'Nama Lengkap', max_length=50)
    no_telp = forms.CharField(label = 'No Telepon', max_length=20)

class KonsumenRoleForm(forms.Form):
    email = forms.CharField(label = 'Email', max_length=50)
    password = forms.CharField(label = 'Password',  widget=forms.PasswordInput, max_length=128)
    nama_lengkap = forms.CharField(label = 'Nama Lengkap', max_length=50)
    no_telp = forms.CharField(label = 'No Telepon',max_length=20)
    jenis_kelamin = forms.CharField(label = 'Jenis Kelamin', max_length=1)
    tanggal_lahir = forms.CharField(label = 'Tanggal Lahir (yyyy-mm-dd)', max_length=10)

class KurirRoleForm(forms.Form):
    email = forms.CharField(label = 'Email', max_length=50)
    password = forms.CharField(label = 'Password',  widget=forms.PasswordInput, max_length=128)
    nama_lengkap = forms.CharField(label = 'Nama Lengkap', max_length=50)
    no_telp = forms.CharField(label = 'No Telepon', max_length=20)
    nama_perusahaan = forms.CharField(label = 'Nama Perusahaan', max_length=50)

class CSRoleForm(forms.Form):
    email = forms.CharField(label = 'Email', max_length=50)
    password = forms.CharField(label = 'Password',  widget=forms.PasswordInput, max_length=128)
    nama_lengkap = forms.CharField(label = 'Nama Lengkap', max_length=50)
    no_telp = forms.CharField(label = 'No Telepon', max_length=20)
    no_ktp = forms.CharField(label = 'No KTP', max_length=20)
    no_sia = forms.CharField(label = 'Nomor SIA', max_length=20)
    

login/views.py
from django.shortcuts import render, redirect
from .forms import LoginForm, ChoiceRoleForm, AdminRoleForm, KonsumenRoleForm, KurirRoleForm, CSRoleForm
from django.db import connection
from collections import namedtuple
from random import randrange

def namedtuplefetchall(cursor):
    "Return all rows from a cursor as a namedtuple"
    desc = cursor.description
    nt_result = namedtuple('Result', [col[0] for col in desc])
    return [nt_result(*row) for row in cursor.fetchall()]

def index(request, validasi = None):
    try:
        email = request.session['email']
        return login(request)
    except KeyError:
        formulir = LoginForm()
        message = ""
        if(validasi==False):
            message = "Invalid email or password"
        argument = { 
            'formlogin' : formulir,
            'message' : message
        }
        return render(request, 'login.html', argument)
    
def login(request):
    try:
        email = request.session['email']
        password = request.session['password']
    except:
        email = request.POST['email']
        password = request.POST['password']

    email = str(email)
    password = str(password)
    cursor = connection.cursor()
    cursor.execute("set search_path to farmakami")
    cursor.execute("select * from pengguna where email='"+email+"' and password='"+password+"'")
    hasil = namedtuplefetchall(cursor)
    role = cekRole(email)
    roleAdmin = False
    roleKonsumen = False
    roleKurir = False
    roleCS = False
    if (role == 'Admin'):
        roleAdmin = True
    if (role == 'Konsumen'):
        roleKonsumen = True
    if (role == 'Kurir'):
        roleKurir = True
    if (role == 'CS'):
        roleCS = True

    cursor.execute("set search_path to public")
    if (hasil == []):
        cursor.close()
        return index(request, False)
    else:
        request.session['email'] = hasil[0].email
        request.session['telepon'] = hasil[0].telepon
        request.session['password'] = hasil[0].password
        request.session['nama_lengkap'] = hasil[0].nama_lengkap
        request.session.set_expiry(1800)
        request.session['role'] = role
        argument = {
            'hasil' : hasil,
            'roleAdmin' : roleAdmin,
            'roleKonsumen' : roleKonsumen,
            'roleKurir' : roleKurir,
            'roleCS' : roleCS
        }
        cursor.close()
        return render(request, "home.html", argument)

def logout(request):
    request.session.flush()
    request.session.clear_expired()
    return index(request)

def profil(request):
    try:
        email = request.session['email']
    except Exception as e:
        return redirect('/')
    cursor = connection.cursor()
    cursor.execute("set search_path to farmakami")
    cursor.execute("select * from pengguna where email='"+email+"'")
    pengguna = namedtuplefetchall(cursor)

    role = cekRole(email)
    roleAdmin = False
    roleKonsumen = False
    roleKurir = False
    roleCS = False
    if (role == 'Admin'):
        roleAdmin = True
    if (role == 'Konsumen'):
        roleKonsumen = True
    if (role == 'Kurir'):
        roleKurir = True
    if (role == 'CS'):
        roleCS = True
        
    if (roleAdmin):
        cursor.execute("select id_apotek from admin_apotek where email='"+email+"'")
        id_apotek = namedtuplefetchall(cursor)
        id_apotek = id_apotek[0].id_apotek

        argument = {
            'hasil' : pengguna,
            'role' : role,
            'id_apotek' : id_apotek,
            'roleAdmin' : roleAdmin,
            'roleKonsumen' : roleKonsumen,
            'roleKurir' : roleKurir,
            'roleCS' : roleCS
        }
    elif (roleKurir):
        cursor.execute("select * from kurir where email='"+email+"'")
        kurir = namedtuplefetchall(cursor)
        id_kurir = kurir[0].id_kurir
        nama_perusahaan = kurir[0].nama_perusahaan
        argument = {
            'hasil' : pengguna,
            'role' : role,
            'id_kurir' : id_kurir,
            'nama_perusahaan' : nama_perusahaan,
            'roleAdmin' : roleAdmin,
            'roleKonsumen' : roleKonsumen,
            'roleKurir' : roleKurir,
            'roleCS' : roleCS
        }
    elif (roleKonsumen):
        cursor.execute("select * from konsumen where email='"+email+"'")
        konsumen = namedtuplefetchall(cursor)
        id_konsumen = str(konsumen[0].id_konsumen)
        jenis_kelamin = konsumen[0].jenis_kelamin
        tanggal_lahir = konsumen[0].tanggal_lahir
        cursor.execute("select * from alamat_konsumen where id_konsumen='"+id_konsumen+"'")
        data_alamat = namedtuplefetchall(cursor)
        argument = {
            'hasil' : pengguna,
            'role' : role,
            'id_konsumen' : id_konsumen,
            'jenis_kelamin' : jenis_kelamin,
            'tanggal_lahir' : tanggal_lahir,
            'data_alamat' : data_alamat,
            'roleAdmin' : roleAdmin,
            'roleKonsumen' : roleKonsumen,
            'roleKurir' : roleKurir,
            'roleCS' : roleCS
        }
    elif (roleCS):
        cursor.execute("select * from cs where email='"+email+"'")
        cs = namedtuplefetchall(cursor)
        no_ktp = cs[0].no_ktp
        no_sia = cs[0].no_sia
        argument = {
            'hasil' : pengguna,
            'role' : role,
            'no_ktp' : no_ktp,
            'no_sia' : no_sia,
            'roleAdmin' : roleAdmin,
            'roleKonsumen' : roleKonsumen,
            'roleKurir' : roleKurir,
            'roleCS' : roleCS
        }
    else:
        argument = {
            'hasil' : pengguna,
            'role' : role,
            'roleAdmin' : roleAdmin,
            'roleKonsumen' : roleKonsumen,
            'roleKurir' : roleKurir,
            'roleCS' : roleCS
        }

    cursor.close()
    return render(request, "profil.html", argument)

    
def cekRole(email):
    cursor = connection.cursor()
    cursor.execute("set search_path to farmakami")
    cursor.execute("select * from pengguna where email='"+email+"'")
    pengguna = namedtuplefetchall(cursor)
    cursor.execute("select * from admin_apotek where email='"+email+"'")
    hasil = namedtuplefetchall(cursor)
    if (hasil != []):
        cursor.close()
        return "Admin"
    else:
        cursor.execute("select * from kurir where email='"+email+"'")
        hasil = namedtuplefetchall(cursor)
        if (hasil != []):
            cursor.close()
            return "Kurir"
        else:
            cursor.execute("select * from cs where email='"+email+"'")
            hasil = namedtuplefetchall(cursor)
            if (hasil != []):
                cursor.close()
                return "CS"
            else:
                cursor.execute("select * from konsumen where email='"+email+"'")
                hasil = namedtuplefetchall(cursor)
                if (hasil != []):
                    cursor.close()
                    return "Konsumen"

def registerPengguna(request):
    formulir = ChoiceRoleForm()
    argument = { 
        'form' : formulir,
        'formrole' : True,
        'roleAdmin' : False,
        'roleKonsumen' : False,
        'roleKurir' : False,
        'roleCS' : False
    }
    return render(request, 'registerPengguna.html', argument)

def registerPenggunaRole(request, message="", role=None):
    try:
        Role = str(request.POST['Role'])
    except:
        Role = role
    roleAdmin = False
    roleKonsumen = False
    roleKurir = False
    roleCS = False
    if(Role == "Admin"):
        formulir = AdminRoleForm()
        roleAdmin = True
    elif(Role == "Konsumen"):
        formulir = KonsumenRoleForm()
        roleKonsumen = True
    elif(Role == "Kurir"):
        formulir = KurirRoleForm()
        roleKurir = True
    else :
        formulir = CSRoleForm()
        roleCS = True

    argument = { 
        'form' : formulir,
        'role' : Role,
        'roleAdmin' : roleAdmin,
        'roleKonsumen' : roleKonsumen,
        'roleKurir' : roleKurir,
        'roleCS' : roleCS,
        'message': message
    }
    return render(request, 'registerPengguna.html', argument)

def insertAdmin(request):
    email = str(request.POST['email'])
    password = str(request.POST['password'])
    nama_lengkap = str(request.POST['nama_lengkap'])
    no_telp = str(request.POST['no_telp'])

    cursor = connection.cursor()
    cursor.execute("set search_path to farmakami")
    cursor.execute("select count(*) as c from apotek")
    hasil = namedtuplefetchall(cursor)
    hasil2 = int(hasil[0].c)
    cursor.execute("select * from pengguna where email='"+email+"'")
    hasil = namedtuplefetchall(cursor)
    if (hasil == []):
        cursor.execute("insert into pengguna values ('"+email+"','"+no_telp+"','"+password+"','"+nama_lengkap+"')")
        cursor.execute("insert into apoteker values ('"+email+"')")
        while True:
            try:
                id_apotek = str(randrange(hasil2)+1)
                cursor.execute("insert into admin_apotek values ('"+email+"','"+id_apotek+"')")
                break
            except Exception as e:
                continue
    else:
        cursor.close()
        return registerPenggunaRole(request, "Email sudah digunakan", 'Admin')
                
    cursor.execute("select * from pengguna where email='"+email+"' and password='"+password+"'")
    hasil = namedtuplefetchall(cursor)

    if (hasil == []):
        cursor.close()
        return index(request, False)
    else:
        cursor.execute("set search_path to public")
        request.session['email'] = hasil[0].email
        request.session['telepon'] = hasil[0].telepon
        request.session['password'] = hasil[0].password
        request.session['nama_lengkap'] = hasil[0].nama_lengkap
        request.session.set_expiry(1800)
        request.session['role'] = 'Admin'
        argument = {
            'hasil' : hasil,
            'roleAdmin' : True,
            'roleKonsumen' : False,
            'roleKurir' : False,

login/templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    Home
{% endblock title %}


{% block content %}
    {%for row in hasil %}
    <div class="container-fluid header">
        <div class="container">
            
            <h1 class="welcome">Selamat Datang di <b>FarmaKami</b>,</h1>
            <h1>{{row.nama_lengkap}}</h1>
            <a href="{% url 'profil' %}" class="mybutton butwhite" role="button">Profil Saya</a>
        </div>
    </div>
    {% endfor %}
    <div class="container justify-content-center">
        <div style="height: 40px;"></div>
        <h2 style="text-align: center;">Pilih Tabel</h2>
        <div style="height: 20px;"></div>
        <div class="row">
            <div class="col">
                <div class="menu">
                    {% if roleAdmin %}
                    <a class="add_item" href="{% url 'balaipengobatan:bpcreate' %}">+</a>
                    {% endif %}
                    <a href="{% url 'balaipengobatan:bplist' %}">
                        <div>
                            <img src="{% static 'images/icons/balai.svg' %}"alt="">
                            <p>Balai Pengobatan</p>
                            <div style="height: 30px;"></div>
                        </div>
                    </a>
                </div>
            </div>
            <div class="col">
                <div class="menu">
                    {% if roleAdmin %}
                    <a class="add_item" href="{% url 'apotek:createApotek' %}">+</a>
                    {% endif %}
                    <a href="{% url 'apotek:tableApotek' %}">
                        <div>
                            <img src="{% static 'images/icons/apotek.svg' %}"alt="">
                            <p>Apotek</p>
                            <div style="height: 30px;"></div>
                        </div>
                    </a>
                </div>
            </div>
            <div class="col">
                <div class="menu">
                    {% if roleAdmin %}
                    <a class="add_item" href="{% url 'produkApotek:createProdukApotek' %}">+</a>
                    {% endif %}
                    <a href="{% url 'produkApotek:tableProdukApotek' %}">
                        <div>
                            <img src="{% static 'images/icons/produk_apotek.svg' %}"alt="">
                            <p>Produk Apotek</p>
                            <div style="height: 30px;"></div>
                        </div>
                    </a>
                </div>
            </div>
            <div class="col">
                <div class="menu">
                    {% if roleAdmin or roleCS %}
                    <a class="add_item" href="{% url 'obat:obatcreate' %}">+</a>
                    {% endif %}
                    <a href="{% url 'obat:obatlist' %}">
                        <div>
                            <img src="{% static 'images/icons/obat.svg' %}"alt="">
                            <p>Obat</p>
                            <div style="height: 30px;"></div>
                        </div>
                    </a>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col">
                <div class="menu">
                    {% if roleAdmin or roleCS %}
                    <a class="add_item" href="/form_create_alat_medis/">+</a>
                    {% endif %}
                    <a href="/read_alat_medis/">
                        <div>
                            <img src="{% static 'images/icons/alat_medis.svg' %}"alt="">
                            <p>Alat Medis</p>
                            <div style="height: 30px;"></div>
                        </div>
                    </a>
                </div>
            </div>
            <div class="col">
                <div class="menu">
                    {% if roleAdmin %}
                    <a class="add_item" href="{% url 'pengantaran_farmasi:createPengantaranFarmasi' %}">+</a>
                    {% endif %}
                    <a href="{% url 'pengantaran_farmasi:readPengantaranFarmasi' %}">
                        <div>
                            <img src="{% static 'images/icons/pengantaran.svg' %}"alt="">
                            <p>Pengantaran Farmasi</p>
                            <div style="height: 30px;"></div>
                        </div>
                    </a>
                </div>
            </div>
            <div class="col">
                <div class="menu">
                    {% if roleAdmin %}
                    <a class="add_item" href="{% url 'produk_dibeli:createProdukDibeli' %}">+</a>
                    {% endif %}
                    <a href="{% url 'produk_dibeli:readProdukDibeli' %}">
                        <div>
                            <img src="{% static 'images/icons/produk_dibeli.svg' %}"alt="">
                            <p>Produk Dibeli</p>
                            <div style="height: 30px;"></div>
                        </div>
                    </a>
                </div>
            </div>
            <div class="col">
                <div class="menu">
                    {% if roleAdmin or roleCS %}
                    <a class="add_item" href="/form_create_transaksi_resep/">+</a>
                    {% endif %}
                    <a href="/read_transaksi_resep/">
                        <div>
                            <img src="{% static 'images/icons/transaksi_resep.svg' %}"alt="">
                            <p>Transaksi Resep</p>
                            <div style="height: 30px;"></div>
                        </div>
                    </a>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

login/templates/homeBck.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="/static/css/home.css">
    <link href='http://fonts.googleapis.com/css?family=Cookie' rel='stylesheet' type='text/css'>
    <title>home</title>
</head>
<body>

    <div class="container-fluid">
        <div class="col-md-8 offset-md-2 mt-5">
            <div class="jumbotron">
                <h1 class="header">Homepage FarmaKami</h1>
                <hr class="my-4">
                <br>
                {%for row in hasil %}
                    <h5 class="welcomeText">Selamat Datang 
                    <br>
                    <p class="userName"><i>{{row.nama_lengkap}}</i></p>
                    <a href="{% url 'profil' %}" class="btn btn-profil" role="button">PROFIL SAYA</a>
                    </h5>
                    <!-- <h5 class="infoUser">{{row.nama_lengkap}}</h>  -->
                {% endfor %}
                        

                <br><br><br>

                <p class="title" style="text-align: center;">Balai Pengobatan & Apotek</p>
                <div class="row justify-content-center">
                    <a href="{% url 'balaipengobatan:bpcreate' %}" class="btn btn-secondary" role="button">Buat Balai Pengobatan</a>
                    <a href="{% url 'balaipengobatan:bplist' %}" class="btn btn-secondary" role="button">List Balai Pengobatan</a>
                    <a href="{% url 'apotek:createApotek' %}" class="btn btn-secondary" role="button">Buat Apotek</a>
                    <a href="{% url 'apotek:tableApotek' %}" class="btn btn-secondary" role="button">Daftar Apotek</a>
                </div>

                <br><br>

                <p class="title" style="text-align: center;">Produk-Apotek</p>
                <div class="row justify-content-center">
                    <a href="{% url 'produkApotek:createProdukApotek' %}" class="btn btn-secondary" role="button">Buat Produk-Apotek</a>
                    <a href="{% url 'produkApotek:tableProdukApotek' %}" class="btn btn-secondary" role="button">Daftar Produk-Apotek</a>
                </div>
                
                <br><br>

                <p class="title" style="text-align: center;">Obat & Alat Medis</p>
                <div class="row justify-content-center">
                    <a href="{% url 'obat:obatcreate' %}" class="btn btn-secondary" role="button">Buat Obat</a>
                    <a href="{% url 'obat:obatlist' %}" class="btn btn-secondary" role="button">List Obat</a>
                    <a href="/form_create_alat_medis/" class="btn btn-secondary" role="button">Buat Alat Medis</a>
                    <a href="/read_alat_medis/" class="btn btn-secondary" role="button">Daftar Alat Medis </a>
                </div>
                

                <br><br>

                <p class="title" style="text-align: center;">List Produk Dibeli</p>
                <div class="row justify-content-center">
                    <a href="{% url 'produk_dibeli:createProdukDibeli' %}" class="btn btn-secondary" role="button">Buat List Produk Dibeli</a>
                    <a href="{% url 'produk_dibeli:readProdukDibeli' %}" class="btn btn-secondary" role="button">Daftar Produk Dibeli</a>
                </div>

                <br><br>

                <p class="title" style="text-align: center;">Pengantaran Farmasi</p>
                <div class="row justify-content-center">
                    <a href="{% url 'pengantaran_farmasi:createPengantaranFarmasi' %}" class="btn btn-secondary" role="button">Buat Pengantaran Farmasi</a>
                    <a href="{% url 'pengantaran_farmasi:readPengantaranFarmasi' %}" class="btn btn-secondary" role="button">Daftar Pengantaran Farmasi</a>
                </div>

                <br><br>

                <p class="title" style="text-align: center;">Transaksi Pembelian & Transaksi Resep</p>
                <div class="row justify-content-center">
                    <a href="/formCT/" class="btn btn-secondary" role="button">Buat Transaksi Pembelian</a>
                    <a href="/readTP/" class="btn btn-secondary" role="button">Daftar Transaksi Pembelian</a>
                    <a href="/form_create_transaksi_resep/" class="btn btn-secondary" role="button">Buat Transaksi Resep</a>
                    <a href="/read_transaksi_resep/" class="btn btn-secondary" role="button">Daftar Transaksi Resep</a>
                </div>

                <br><br><br>

            </div>
        </div>
    </div>

                
    
</body>
</html>