BalaiPengobatan_Obat/urls.py
from django.urls import path, include
from django.contrib import admin
from .views import bpcreate, bplist, obatcreate, obatlist, updatebp, updateobat, deletebp, deleteobat

app_name = "balaipengobatan"
urlpatterns = [
    path('createBalaiPengobatan', bpcreate, name="bpcreate"),
    path('listBalaiPengobatan', bplist, name="bplist"),
    path('updateBalaiPengobatan/<str:id_balai>', updatebp, name="updatebp"),
    path('deleteBalaiPengobatan/<str:id_balai>', deletebp, name="deletebp"),
    path('createObat', obatcreate, name="obatcreate"),
    path('listObat', obatlist, name="obatlist"),
    path('updateObat/<str:id_obat>/<str:id_produk>/<str:id_merk_obat>', updateobat, name="updateobat"),
    path('deleteObat/<str:id_obat>/<str:id_produk>', deleteobat, name="deleteobat"),
]

TK4/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('login.urls')),
    path('', include('Transaksi_Pembelian.urls')),
    path('', include(('ListProdukDibeli_PengantaranFarmasi.urls','produk_dibeli'), namespace='produk_dibeli')),
    path('', include(('ListProdukDibeli_PengantaranFarmasi.urls', 'pengantaran_farmasi'), namespace='pengantaran_farmasi')),
    path('balaipengobatan/', include(('BalaiPengobatan_Obat.urls', 'balaipengobatan'), namespace='balaipengobatan')),
    path('obat/', include(('BalaiPengobatan_Obat.urls', 'obat'), namespace='obat')),
    path('apotek/', include('apotek.urls')),
    path('produkApotek/', include('produkApotek.urls')),
    path('', include('TransaksiResep_AlatMedis.urls'))
]

BalaiPengobatan_Obat/models.py
from django.db import models

# Create your models here.

BalaiPengobatan_Obat/forms.py
from django import forms
from django.db import connection
from collections import namedtuple

cursor = connection.cursor()
cursor.execute("select id_apotek from farmakami.apotek")
select = cursor.fetchall()
id_apotek_berasosiasi = [tuple([select[x][0], select[x][0]]) for x in range(len(select))]

def namedtuplefetchall(cursor):
    "Return all rows from a cursor as a namedtuple"
    desc = cursor.description
    nt_result = namedtuple('Result', [col[0] for col in desc])
    return [nt_result(*row) for row in cursor.fetchall()]

class createBalaiPengobatanForms(forms.Form):
    alamat_balai = forms.CharField(label='Alamat Balai', max_length=100)
    nama_balai = forms.CharField(label='Nama Balai', max_length=20)
    jenis_balai = forms.CharField(label='Jenis Balai', max_length=20)
    telepon_balai = forms.CharField(label='Telepon Balai', required= False, max_length=20)
    id_apotek = forms.CharField(max_length=10, widget=forms.Select(choices=id_apotek_berasosiasi, attrs={'class': 'form-control','placeholder' : 'Apotek Bersosiasi','required': True,}))

class createObatForm(forms.Form):
    # id_merk_obat = forms.CharField(label='ID Merk Obat', max_length=10, widget=forms.Select(choices=ID_MERK_OBAT))
    netto = forms.CharField(label='Netto', max_length=10)
    dosis = forms.CharField(label='Dosis', max_length=100)
    aturan_pakai = forms.CharField(label='Aturan Pakai', required= False, max_length=100)
    kontraindikasi = forms.CharField(label='Kontraindikasi', required= False, max_length=100)
    bentuk_kesediaan = forms.CharField(label='Bentuk Kesediaan', max_length=100)

class updateBalaiPengobatanForms(forms.Form):
    id_balai = forms.CharField(label='ID Balai', max_length=10, disabled = True, widget = forms.TextInput(attrs={'readonly':'readonly'}))
    alamat_balai = forms.CharField(label='Alamat Balai', max_length=100)
    nama_balai = forms.CharField(label='Nama Balai', max_length=20)
    jenis_balai = forms.CharField(label='Jenis Balai', max_length=20)
    telepon_balai = forms.CharField(label='Telepon Balai', required= False, max_length=20)
    id_apotek = forms.CharField(max_length=10 ,widget=forms.Select(choices=id_apotek_berasosiasi, attrs={'class': 'form-control','required': True,}))

class updateObatForm(forms.Form):
    id_obat = forms.CharField(label='ID Obat', max_length=10, disabled = True, widget = forms.TextInput(attrs={'readonly':'readonly'}))
    id_produk = forms.CharField(label='ID Produk', max_length=10, disabled = True, widget = forms.TextInput(attrs={'readonly':'readonly'}))
    netto = forms.CharField(label='Netto', max_length=10)
    dosis = forms.CharField(label='Dosis', max_length=100)
    aturan_pakai = forms.CharField(label='Aturan Pakai', required= False, max_length=100)
    kontraindikasi = forms.CharField(label='Kontraindikasi', required= False, max_length=100)
    bentuk_kesediaan = forms.CharField(label='Bentuk Kesediaan', max_length=100)
    


    
    

BalaiPengobatan_Obat/views.py
# Create your views here.
from django.shortcuts import render, reverse, redirect
from .forms import createBalaiPengobatanForms, updateBalaiPengobatanForms, createObatForm, updateObatForm
import pandas as pd
from django_tables2.tables import Table
from django.contrib.staticfiles import finders
from django.contrib.staticfiles.storage import staticfiles_storage
from django.contrib.auth.models import User, Permission
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import authenticate, logout, login
from django.conf.urls.static import static
from .forms import *
from django.db import connection
from collections import namedtuple
from django.http import HttpResponseRedirect
from django.db import IntegrityError


#GENERAL FUNCTION
def namedtuplefetchall(cursor):
    "Return all rows from a cursor as a namedtuple"
    desc = cursor.description
    nt_result = namedtuple('Result', [col[0] for col in desc])
    return [nt_result(*row) for row in cursor.fetchall()]

#INPUT obat
def get_input_obat(request):
    input = request.POST
    netto = input['netto']
    dosis = input['dosis']
    aturan_pakai = input['aturan_pakai']
    kontraindikasi = input['kontraindikasi']
    bentuk_kesediaan = input['bentuk_kesediaan']
    return [netto,dosis,aturan_pakai,kontraindikasi,bentuk_kesediaan]

#Create obat FUNCTION
def obatcreate(request):
    message =""
    cursor = connection.cursor()
    cursor.execute("set search_path to farmakami")
    cursor.execute("select id_merk_obat from merk_obat order by cast(id_merk_obat as int)")
    id_merk_obat_view = namedtuplefetchall(cursor)

    if request.method =='POST':
        input = get_input_obat(request)
        id_merk_obat = request.POST['id_merk_obat']
        cursor = connection.cursor()
        cursor.execute("set search_path to farmakami")
        cursor.execute("select id_obat as c from obat order by id_obat::int asc")
        id_obat = namedtuplefetchall(cursor)
        id_obat = id_obat[-1].c
        cursor.execute("select id_produk as c from obat order by id_produk::int asc")
        id_produk = namedtuplefetchall(cursor)
        id_produk = id_produk[-1].c
        id_obat = int(id_obat) + 1
        idString1 = str(id_obat)
        id_produk = int(id_produk) + 1
        idString2 = str(id_produk)
        
        try :
            cursor.execute("insert into obat values ('"+idString1+"','"+idString2+"','"+id_merk_obat+"','"+input[0]+"','"+input[1]+"','"+input[2]+"','"+input[3]+"','"+input[4]+"')")
            cursor.close()
            return redirect('/obat/listObat')
        except:
            message = "Data tidak berhasil dibuat"

    form = createObatForm()
    
    args = {
        'id_merk_obat': id_merk_obat_view,
        'form': form,
        'message' : message
        }
    return render(request, "createObat.html", args)

#READ obat FUNCTION
def obatlist(request):
    cursor = connection.cursor()
    roleAdmin = False
    roleKonsumen = False
    roleKurir = False
    roleCS = False
    
    try:
        if (request.session['role'] == 'Admin'):
            roleAdmin = True
        if (request.session['role'] == 'Konsumen'):
            roleKonsumen = True
        if (request.session['role'] == 'Kurir'):
            roleKurir = True
        if (request.session['role'] == 'CS'):
            roleCS = True
    except:
        return redirect('/')

    email = str(request.session['email'])
    cursor.execute("set search_path to farmakami")
    cursor.execute("select * from obat order by cast(id_obat as int)")
    hasil = namedtuplefetchall(cursor)
    cursor.close()
    argument = {
        'table' : hasil,
        'roleAdmin' : roleAdmin,
        'roleKonsumen' : roleKonsumen,
        'roleKurir' : roleKurir,
        'roleCS' : roleCS
    }
    return render(request, "listObat.html", argument)

#UPDATE obat FUNCTION
def updateobat(request, id_obat, id_produk, id_merk_obat, success=True):
    message =""
    id_obat = str(id_obat)
    id_produk = str(id_produk)
    id_merk_obat = str(id_merk_obat)
    id_merk_obat_new = str(id_merk_obat)
    cursor = connection.cursor()
    cursor.execute("set search_path to farmakami")
    cursor.execute("select id_merk_obat from merk_obat order by cast(id_merk_obat as int)")
    id_merk_obat_view = namedtuplefetchall(cursor)
    cursor.execute("select * from obat where id_obat = '"+id_obat+"' and id_produk = '"+id_produk+"'")
    hasil = namedtuplefetchall(cursor)
    id_obat = hasil[0].id_obat
    id_produk = hasil[0].id_produk
    netto = hasil[0].netto
    dosis = hasil[0].dosis
    aturan_pakai = hasil[0].aturan_pakai
    kontraindikasi = hasil[0].kontraindikasi
    bentuk_kesediaan = hasil[0].bentuk_kesediaan
    
    form = updateObatForm(initial={
        'id_obat': id_obat, 'id_produk': id_produk, 'netto': netto, 'dosis': dosis, 'aturan_pakai': aturan_pakai, 'kontraindikasi': kontraindikasi, 'bentuk_kesediaan': bentuk_kesediaan })
    if request.method == 'POST':
        input = get_input_obat(request)
        id_merk_obat_new = request.POST['id_merk_obat']
        print(input)
        try :
            cursor.execute("update obat set id_merk_obat ='"+id_merk_obat_new+"', netto ='"+input[0]+"', dosis ='"+input[1]+"', aturan_pakai ='"+input[2]+"', kontraindikasi ='"+input[3]+"', bentuk_kesediaan ='"+input[4]+"' where id_obat = '"+id_obat+"' and id_produk = '"+id_produk+"'")
            cursor.close()
            message = "Data berhasil diubah"
            return redirect('/obat/listObat')
        except:
            message = "Data tidak berhasil diubah"
            

    
    argument = {
        'form' : form,
        'message' : message,
        'id_obat' : id_obat,
        'id_produk' : id_produk,
        'idMerkObatForm' : id_merk_obat,
        'id_merk_obat': id_merk_obat_view,
    }
    return render(request, "updateObat.html", argument)

#DELETE obat FUNCTION
def deleteobat(request, id_obat, id_produk):
    message =""
    id_obat = str(id_obat)
    id_produk = str(id_produk)
    cursor = connection.cursor()
    roleAdmin = False
    roleKonsumen = False
    roleKurir = False
    roleCS = False

    try:
        if (request.session['role'] == 'Admin'):
            roleAdmin = True
        if (request.session['role'] == 'Konsumen'):
            roleKonsumen = True
        if (request.session['role'] == 'Kurir'):
            roleKurir = True
        if (request.session['role'] == 'CS'):
            roleCS = True
    except:
        return redirect('/')


    email = str(request.session['email'])
    cursor.execute("set search_path to farmakami")
    cursor.execute("delete from obat where id_obat ='"+id_obat+"' and id_produk = '"+id_produk+"'")
    cursor.execute("select * from obat order by cast(id_obat as int)")
    hasil = namedtuplefetchall(cursor)
    cursor.close()
    message = "Data berhasil dihapus"
    argument = {
        'table' : hasil,
        'message' : message,
        'roleAdmin' : roleAdmin,
        'roleKonsumen' : roleKonsumen,
        'roleKurir' : roleKurir,
        'roleCS' : roleCS
    }
    return render(request, "listObat.html", argument)

#INPUT balai_pengobatan
def get_input_balai_pengobatan(request):
    input = request.POST
    alamat_balai = input['alamat_balai']
    nama_balai = input['nama_balai']
    jenis_balai = input['jenis_balai']
    telepon_balai = input['telepon_balai']
    return [alamat_balai,nama_balai,jenis_balai,telepon_balai]

#CREATE balai_pengobatan FUNCTION
def bpcreate(request):
    message =""
    if request.method =='POST':
        input = get_input_balai_pengobatan(request)
        form = createBalaiPengobatanForms(request.POST)
        if form.is_valid():
            cursor = connection.cursor()
            cursor.execute("set search_path to farmakami")
            cursor.execute("select id_balai as c from balai_pengobatan order by id_balai::int asc")
            id_balai = namedtuplefetchall(cursor)
            id_balai = id_balai[-1].c
            id_balai = int(id_balai) + 1
            idString = str(id_balai)
            id_apotek = form.cleaned_data['id_apotek']
            
            try :
                cursor.execute("insert into balai_pengobatan values ('"+idString+"','"+input[0]+"','"+input[1]+"','"+input[2]+"','"+input[3]+"')")
                cursor.execute("INSERT INTO balai_apotek VALUES (%s, %s)",
                        [id_balai, id_apotek])
                cursor.close()
                return redirect('/balaipengobatan/listBalaiPengobatan')
            except:
                message = "Data tidak berhasil dibuat"

    form = createBalaiPengobatanForms()
    args = {
        'form': form,
        'message' : message
        }
    return render(request, 'createBalaiPengobatan.html', args)

#READ balai_pengobatan FUNCTION
def bplist(request):
    cursor = connection.cursor()
    roleAdmin = False
    roleKonsumen = False
    roleKurir = False
    roleCS = False

    try:
        if (request.session['role'] == 'Admin'):
            roleAdmin = True
        if (request.session['role'] == 'Konsumen'):
            roleKonsumen = True
        if (request.session['role'] == 'Kurir'):
            roleKurir = True
        if (request.session['role'] == 'CS'):
            roleCS = True
    except:
        return redirect('/')

    email = str(request.session['email'])

    cursor.execute("set search_path to farmakami")
    cursor.execute("select p.id_balai, alamat_balai, nama_balai, jenis_balai, telepon_balai, id_apotek from balai_pengobatan as p left join balai_apotek as a on a.id_balai = p.id_balai order by p.id_balai::int asc")
    hasil = namedtuplefetchall(cursor)
    # cursor.execute("SELECT id_apotek FROM BALAI_PENGOBATAN as bp JOIN BALAI_APOTEK as ba ON bp.id_balai = ba.id_balai")
    # id_apotek_view = namedtuplefetchall(cursor)
    cursor.close()
    argument = {

BalaiPengobatan_Obat/templates/createBalaiPengobatan.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    Create Balai Pengobatan
{% endblock title %}


{% block content %}
<div class="container justify-content-center align-items-center">
    <h1 class="list_title">Create Balai Pengobatan</h1>
    <h2 class="message">{{message}}</h2>
    <br>
        <div class="row justify-content-center">
        <div class="login">      
            <form  method="POST" action="{% url 'balaipengobatan:bpcreate' %}">
            {% csrf_token %}
                <div class="loginForm">{{ form.as_p }}</div>
                <br>
                <!-- <label class="loginForm" for="asosiasi">Daftar ID Apotek berasosiasi:</label>
                <select class="form-control" name="asosiasi" id="asosiasi_select exampleSelect1">
                    {% for item in table %}
                    <option value="{{item.asosiasi}}">{{ item.asosiasi }}</option>
                    {% endfor %}
                </select> -->
                <br>             
                <input type="submit" value="Create" name="tombol" class="mybutton">
            </form>
            
        </div>
    </div>
</div>
{% endblock content %}

BalaiPengobatan_Obat/templates/createObat.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    Create Obat
{% endblock title %}


{% block content %}
<div class="container justify-content-center align-items-center">
  <h1 class="list_title">Create Obat</h1>
  <h2 class="message">{{message}}</h2>
  <br>
  <div class="row justify-content-center">
    <div class="login">      
      <form  method="POST" action="{% url 'obat:obatcreate' %}">
        {% csrf_token %}

        <label class="label" style="color: white;" for="id_merk_obat">ID Merk Obat:</label>
  
        <select class="form-control" name="id_merk_obat" id="id_merk_obat" >
          {%for row in id_merk_obat %}
          <option value="{{row.id_merk_obat}}">{{row.id_merk_obat}}</option>
          {% endfor %}
        </select>

        <br>

        <div class="loginForm">{{ form.as_p }}</div>
        <br>

        <input type="submit" value="Create" name="tombol">
      </form>
      
    </div>
  </div>
</div>
{% endblock content %}

BalaiPengobatan_Obat/templates/listBalaiPengobatan.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    Balai Pengobatan
{% endblock title %}


{% block content %}
<div class="container justify-content-center align-items-center">
  <h1 class="list_title">Balai Pengobatan</h1>
  <h2 class="message">{{message}}</h2>
  
  <div class="row justify-content-center">
    {% if roleAdmin %}
    <a href="{% url 'balaipengobatan:bpcreate' %}" class="mybutton" role="button" style="margin-bottom: 30px;">Create Item</a>
    {% endif %}
    <table class="table table-striped">
      <thead>
        <tr>
            <th scope="row">Id Balai</th>
            <th scope="row">Alamat Balai</th>
            <th scope="row">Nama Balai</th>
            <th scope="row">Jenis Balai</th>
            <th scope="row">Telepon Balai</th>
            <th scope="row">Apotik Asosiasi</th>
            {% if roleAdmin %}
            <th scope="row">Edit</th>
            <th scope="row">Delete</th>
            {% endif %}
        </tr>
      </thead>
      <tbody>
      {% for row in table %}
        <tr>
          <td>{{ row.id_balai }}</td>
          <td>{{ row.alamat_balai }}</td>
          <td>{{ row.nama_balai }}</td>
          <td>{{ row.jenis_balai }}</td>
          <td>{{ row.telepon_balai }}</td>
          <td>{{ row.id_apotek }}</td>
          {% if roleAdmin %}
          <td><a href="{% url 'balaipengobatan:updatebp' row.id_balai %}" class="mybutton butwhite" role="button">EDIT</a></td>
          <td><a href="{% url 'balaipengobatan:deletebp' row.id_balai %}" class="mybutton butred" role="button">DELETE</a></td>
          {% endif %}
        </tr>
      {% endfor %}
      </tbody>
    </table>
  </div>
</div>
{% endblock content %}

BalaiPengobatan_Obat/templates/listObat.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    Obat
{% endblock title %}


{% block content %}
<div class="container justify-content-center align-items-center">
  <h1 class="list_title">Obat</h1>
  <h2 class="message">{{message}}</h2>

  <div class="row justify-content-center">
    {% if roleAdmin %}
    <a href="{% url 'obat:obatcreate' %}" class="mybutton" role="button" style="margin-bottom: 30px;">Create Item</a>
    {% endif %}
    <table class="table table-striped">
        <thead>
        <tr>
            <th scope="col">Id Obat</th>
            <th scope="col">Id Produk</th>
            <th scope="col">Id Merk Obat</th>
            <th scope="col">Netto</th>
            <th scope="col">Dosis</th>
            <th scope="col">Aturan Pakai</th>
            <th scope="col">Kontraindikasi</th>
            <th scope="col">Bentuk Kesediaan</th>
            {% if roleAdmin %}
            <th scope="col">Edit</th>
            <th scope="col">Delete</th>
            {% endif %}
        </tr>
        </thead>
        <tbody class="listObat">
        {% for item in table %}
          <tr>
              <td>{{ item.id_obat }}</td>
              <td>{{ item.id_produk }}</td>
              <td>{{ item.id_merk_obat }}</td>
              <td>{{ item.netto }}</td>
              <td>{{ item.dosis }}</td>
              <td>{{ item.aturan_pakai }}</td>
              <td>{{ item.kontraindikasi }}</td>
              <td>{{ item.bentuk_kesediaan }}</td>
              {% if roleAdmin %}
              <td><a href="{% url 'obat:updateobat' item.id_obat item.id_produk item.id_merk_obat %}" class="mybutton butwhite" role="button">EDIT</a></td>
              <td><a href="{% url 'obat:deleteobat' item.id_obat item.id_produk %}" class="mybutton butred" role="button">DELETE</a></td>
              {% endif %}
          </tr>
        {% endfor %}
        </tbody>
    </table>
  </div>
</div>
{% endblock content %}

BalaiPengobatan_Obat/templates/updateBalaiPengobatan.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    Update Balai Pengobatan
{% endblock title %}


{% block content %}
<div class="container justify-content-center align-items-center">
    <h1 class="list_title">Update Balai Pengobatan</h1>
    <h2 class="message">{{message}}</h2>
    <br>
    <div class="row justify-content-center">
        <div class="login">      
            <form  method="POST" action="{% url 'balaipengobatan:updatebp' id_balai %}">
            {% csrf_token %}

            <div class="loginForm">{{ form.as_p }}</div>
            <br>

            <!-- <label class="loginForm" for="asosiasi">Daftar ID Apotek berasosiasi:</label>
            <select class="form-control" name="asosiasi" id="asosiasi_select exampleSelect1">
                {% for item in table %}
                <option value="{{item.asosiasi}}">{{ item.asosiasi }}</option>
                {% endfor %}
            </select> -->

            <br>
            <input type="submit" value="Update" name="tombol" class="mybutton">
            </form>
            
        </div>
    </div>
</div>
{% endblock content %}

BalaiPengobatan_Obat/templates/updateObat.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    Update Obat
{% endblock title %}


{% block content %}
<div class="container justify-content-center align-items-center">
  <h1 class="list_title">Update Obat</h1>
  <h2 class="message">{{message}}</h2>
  <br>
  <div class="row justify-content-center">
    <div class="login">      
      <form  method="POST" action="{% url 'obat:updateobat' id_obat id_produk id_merk_obat %}">
        {% csrf_token %}
        
        <label class="label" style="color: white;" for="id_merk_obat">ID Merk Obat:</label>

        <select class="form-control" name="id_merk_obat" id="id_merk_obat" >
          {%for row in id_merk_obat %}
          <option value="{{row.id_merk_obat}}">{{row.id_merk_obat}}</option>
          {% endfor %}
        </select>

        <br>
        <div class="loginForm">{{ form.as_p }}</div>
        <br>
        <input type="submit" value="Update" name="tombol">
      </form>
      
    </div>
  </div>
</div>
{% endblock content %}